name: deploy-site

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v8
    - uses: actions/checkout@v2
    - run: nix-build $GITHUB_WORKSPACE
